#!/usr/bin/env python3
"""
Build every table and figure for notes/kan_identifiability/ from COMMITTED
result files. No training. Each generated table carries a header comment naming
its source file and the commit that introduced it, so every number in the note
is traceable.

Run from the repo root:
    python notes/kan_identifiability/build_note.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO = Path(__file__).resolve().parent.parent.parent
RES = REPO / "experiments" / "identifiability_gate" / "results"
OUT = REPO / "notes" / "kan_identifiability"
TAB, FIG = OUT / "tables", OUT / "figures"
sys.path.insert(0, str(REPO / "experiments" / "identifiability_gate"))
from run_kan_seed_variance import raw_and_quotiented  # noqa: E402  (reused metric)

R2_THRESHOLD = 0.999


def load(name: str) -> dict:
    return json.loads((RES / f"{name}.json").read_text())


def commit_of(name: str) -> str:
    p = RES / f"{name}.json"
    try:
        return subprocess.run(["git", "log", "-1", "--format=%h", "--", str(p)],
                               cwd=REPO, capture_output=True, text=True).stdout.strip() or "UNCOMMITTED"
    except Exception:
        return "UNKNOWN"


def write_table(fname: str, sources: list[str], title: str, lines: list[str]) -> None:
    src = "\n".join(f"<!-- source: experiments/identifiability_gate/results/{s}.json "
                    f"@ commit {commit_of(s)} -->" for s in sources)
    (TAB / fname).write_text(f"<!-- {title} -->\n{src}\n<!-- generated by notes/kan_identifiability/"
                              f"build_note.py -- do not hand-edit -->\n\n" + "\n".join(lines) + "\n")
    print(f"  wrote tables/{fname}")


def md(rows: list[list[str]], header: list[str], align: list[str] | None = None) -> list[str]:
    align = align or ["---"] * len(header)
    return ["| " + " | ".join(header) + " |", "| " + " | ".join(align) + " |"] + \
           ["| " + " | ".join(r) + " |" for r in rows]


# ──────────────────────────────── tables ────────────────────────────────────

def t1() -> None:
    m = load("kan_multivariate")
    rows = []
    for key, filt_key, label in [("layer1_x1_edge", "layer1_x1", "layer1 x1-edge"),
                                  ("layer1_x2_edge", "layer1_x2", "layer1 x2-edge"),
                                  ("layer2_edge", "layer2", "layer2 (hidden->out)")]:
        e, f = m[key], m["filtered_edge_comparison"][filt_key]
        rows.append([label,
                     f"{f['raw']['mean']:.4f}", f"{f['quotiented']['mean']:.4f}",
                     f"{f['a']['mean']:+.3f} ± {f['a']['std']:.3f}",
                     f"{e['raw_summary']['mean']:.4f}", f"{e['quotiented_summary']['mean']:.4f}",
                     f"{e['a_summary']['mean']:+.3f} ± {e['a_summary']['std']:.3f}"])
    write_table("T1_additive_d2_layer1.md",
                ["kan_multivariate"],
                "T1. Additive d>=2 edges: 7-seed filtered vs 10-seed unfiltered",
                ["**T1.** Additive d≥2 (`KAN[2→1→1]`, target `exp(-x1)+sin(pi*x2)`). "
                 "Filtered = 7 well-converged seeds / 21 pairs; unfiltered = all 10 seeds / 45 pairs. "
                 "`a` is the fitted affine slope, mean ± SD over pairs.", ""] +
                md(rows, ["edge", "RAW (7-seed)", "QUOTIENTED (7-seed)", "a (7-seed)",
                          "RAW (10-seed)", "QUOTIENTED (10-seed)", "a (10-seed)"]))


def t2() -> None:
    a = load("kan_step10_audit")
    t = {r["regime"]: r for r in a["q10c"]["table"]}
    rows = [[reg,
             f"{t[reg]['layer2_derived_exact']:.4f}",
             f"{t[reg]['layer2_derived_affine']:.4f}",
             f"{t[reg]['layer2_fitted_affine']:.4f}",
             f"{t[reg]['layer2_output_affine']:.4f}"] for reg in ("d=1", "d>=2")]
    write_table("T2_layer2_zero_free_parameters.md",
                ["kan_step10_audit"],
                "T2. Layer2 predicted from layer1, by free-parameter count",
                ["**T2.** Layer2 residual under four tests, ordered by how many parameters are free "
                 "on the layer2 side. The first two columns predict layer2 with **zero** free "
                 "parameters; only the third fits anything to layer2.", "",
                 "- **derived-exact (0 free params):** `phi2_i(u)` vs `phi2_j(h(u))`, with "
                 "`h = phi1_j∘phi1_i^-1` constructed numerically from layer1.",
                 "- **propagated-(a,b) (0 free params):** `phi2_i(u)` vs `phi2_j(a·u+b)`, with `(a,b)` "
                 "taken from layer1's own affine fit.",
                 "- **fitted-affine (2 free params):** `(a,b)` fitted to minimize layer2's residual — "
                 "a best-case upper bound, not a prediction.",
                 "- **output-affine (2 free params):** `phi2_i(u)` vs `A·phi2_j(u)+B` — the "
                 "wrong transform type for a downstream function, shown for contrast.", ""] +
                md(rows, ["regime", "derived-exact (0 free)", "propagated-(a,b) (0 free)",
                          "fitted-affine (2 free)", "output-affine (2 free)"]))


def t3() -> None:
    a = load("kan_step10_audit")
    t = {r["regime"]: r for r in a["q10c"]["table"]}
    rows = []
    for reg in ("d=1", "d>=2"):
        ex, af = t[reg]["layer2_derived_exact"], t[reg]["layer2_derived_affine"]
        rows.append([reg, f"{ex:.4f}", f"{af:.4f}", f"{af/ex:.2f}×"])
    write_table("T3_exact_vs_affine_gap.md",
                ["kan_step10_audit"],
                "T3. Cost of forcing the reparameterization to be affine",
                ["**T3.** What it costs to restrict `h` to the affine subgroup. The gap between an "
                 "exact numerical `h` and an affine one measures how far the realized "
                 "reparameterization is from affine, and is unaffected by d=1's small pair count "
                 "in the way a single residual is.", ""] +
                md(rows, ["regime", "derived-exact", "propagated affine", "cost of forcing affine"]))


def t4() -> None:
    d = load("kan_step10_audit")["q10d"]
    rows = [["within-pair \\|a_x1 − a_x2\\|, absolute", f"{d['within_pair_mean_abs']:.4f}"],
            ["within-pair \\|a_x1 − a_x2\\|, relative", f"{d['within_pair_mean_rel']:.4f} "
                                                     f"({d['within_pair_mean_rel']*100:.1f}%)"],
            ["within-pair worst case, absolute", f"{d['within_pair_max_abs']:.4f}"],
            ["across-pair spread of a, SD", f"{d['across_pair_std']:.4f}"],
            ["across-pair spread of a, range", f"{d['across_pair_range']:.4f}"],
            ["ratio within / across (SD)", f"{d['ratio_within_over_across_std']:.4f}"],
            ["ratio within / across (range)", f"{d['ratio_within_over_across_range']:.4f}"],
            ["→ within-pair agreement is tighter by", f"{1/d['ratio_within_over_across_std']:.0f}×"]]
    write_table("T4_shared_scale_effect_size.md",
                ["kan_step10_audit"],
                "T4. Shared-scale effect size at d>=2",
                ["**T4.** The two layer1 edges of one node (fed by `x1` and `x2`) move together to "
                 "~1% within a pair, while the shared factor itself ranges over roughly [−2.6, +2.3] "
                 "across pairs. 21 well-converged pairs.", ""] +
                md(rows, ["quantity", "value"]))


def t5() -> None:
    s = load("kan_step10b_sensitivity")
    rows = [[f["filter"], str(f["n_pairs"]), f"{f['h_affine_residual']:.4f}",
             f"{f['layer2_derived_affine']:.4f}"] for f in s["filters"]]
    rows.append(["**d=1 (grid=12, hidden=1), R²>0.999 filter**", "3",
                 f"**{s['d1_h_vs_affine']:.4f}**", "0.0416"])
    write_table("T5_h_vs_affine.md",
                ["kan_step10b_sensitivity", "kan_step10_audit"],
                "T5. h-vs-affine across regimes and filter choices",
                ["**T5.** How far the realized reparameterization `h` sits from the affine subgroup, "
                 "and how much that depends on where the convergence bar is drawn. "
                 f"d=1 vs d≥2 (registered filter) = {s['d1_h_vs_affine']:.4f} / 0.0025 = "
                 f"{load('kan_step10_audit')['q10c']['h_contrast_d1_over_d2']:.1f}× "
                 f"(contrast as stored in kan_step10_audit.json, computed at full precision).", ""] +
                md(rows, ["configuration / filter", "n pairs", "h-vs-affine",
                          "layer2 propagated-(a,b)"]))


def t6() -> None:
    m = load("kan_multiplicative")
    s = m["summary"]
    P, A, PW = [], [], []
    for r in m["pairs"]:
        for e in r["edges"].values():
            if e.get("inconclusive"):
                continue
            P.append(e["p"]); A.append(e["affine_residual_full"]); PW.append(e["power_residual"])
    P, A, PW = np.array(P), np.array(A), np.array(PW)
    dev = np.abs(P - 1.0)
    strat = []
    for lo, hi, lbl in [(0, .15, "[0, 0.15)"), (.15, .5, "[0.15, 0.5)"),
                         (.5, 1., "[0.5, 1.0)"), (1., 1e9, "[1.0, ∞)")]:
        k = (dev >= lo) & (dev < hi)
        if k.sum():
            strat.append([lbl, str(int(k.sum())), f"{A[k].mean():.4f}",
                          f"{PW[k].mean():.4f}", f"{A[k].mean()/PW[k].mean():.1f}×"])
    c1 = [r["edges"]["1"]["c"] for r in m["pairs"] if not r["edges"]["1"].get("inconclusive")]
    p1 = [r["edges"]["1"]["p"] for r in m["pairs"] if not r["edges"]["1"].get("inconclusive")]
    corr_pc = float(np.corrcoef(p1, np.log(np.abs(c1)))[0, 1])

    write_table("T6_multiplicative_power_gauge.md",
                ["kan_multiplicative"],
                "T6. Multiplicative node: power vs affine quotient",
                ["**T6.** Multiplicative node (`MultKAN[2→1→1]`, target `exp(-x1)·sin(pi*x2)`), "
                 "8 well-converged seeds / 28 pairs / 56 edge-fits, 0 inconclusive "
                 "(100% of the domain retained on every pair).", "",
                 "**(a) Overall**", ""] +
                md([["affine quotient (full grid)", f"{s['affine_full_mean']:.4f}"],
                    ["affine quotient (matched domain)", f"{s['affine_matched_domain_mean']:.4f}"],
                    ["power quotient", f"{s['power_mean']:.4f}"],
                    ["power advantage overall", f"{s['affine_full_mean']/s['power_mean']:.1f}×"]],
                   ["quantity", "residual"]) +
                ["", "**(b) Stratified by |p − 1|.** Affine is the `p=1` slice of the power group, so "
                 "pairs that land near `p=1` are affine-stable by construction; the two quotients "
                 "separate only as the exponent leaves that slice. "
                 f"corr(|p−1|, affine residual) = {np.corrcoef(dev, A)[0,1]:+.4f}.", ""] +
                md(strat, ["\\|p − 1\\|", "n edges", "affine residual", "power residual",
                           "power advantage"]) +
                ["", "**(c) Shared exponent (P3)**", ""] +
                md([["within-pair relative \\|p1 − p2\\|", f"{s['p3_within_mean']:.4f} "
                                                        f"({s['p3_within_mean']*100:.2f}%)"],
                    ["across-pair SD of p", f"{s['p_across_std']:.4f}"],
                    ["ratio within / across", f"{s['p3_ratio']:.4f}"],
                    ["observed range of p", f"[{P.min():.3f}, {P.max():.3f}]"]],
                   ["quantity", "value"]) +
                ["", f"**(d) Prefactors.** `corr(p, log|c1|) = {corr_pc:+.4f}` — the fitted prefactor "
                 f"is largely determined by the exponent, not an independent coordinate "
                 f"(see methods: the pre-registered torus test is not identifiable as posed)."])


def t7() -> None:
    rows = []
    gs = load("kan_grid_sweep")
    for g in gs["grids"]:
        for s in gs["per_grid"][str(g)]["per_seed"]:
            rows.append([f"d=1 `KAN[1→1→1]` grid={g}", "600", str(s["seed"]),
                         f"{s['final_train_loss']:.3e}", f"{s['test_r2']:.6f}",
                         "yes" if s["test_r2"] > R2_THRESHOLD else "**no**"])
    for name, label, ep in [("kan_multivariate", "d≥2 `KAN[2→1→1]` grid=12", "3000"),
                             ("kan_multiplicative", "mult. `MultKAN[2→1→1]` grid=12", "3000")]:
        for s in load(name)["per_seed"]:
            rows.append([label, ep, str(s["seed"]), f"{s['final_train_loss']:.3e}",
                         f"{s['test_r2']:.6f}",
                         "yes" if s["test_r2"] > R2_THRESHOLD else "**no**"])
    counts = {}
    for r in rows:
        counts.setdefault(r[0], [0, 0])
        counts[r[0]][0] += 1
        counts[r[0]][1] += (r[5] == "yes")
    summary = md([[k, f"{v[1]}/{v[0]}"] for k, v in counts.items()],
                 ["configuration", "passed R² > 0.999"])
    write_table("T7_convergence_census.md",
                ["kan_grid_sweep", "kan_multivariate", "kan_multiplicative"],
                "T7. Per-seed convergence census, every run",
                [f"**T7.** Every training run behind this note. Filter threshold: test "
                 f"R² > {R2_THRESHOLD}, applied identically everywhere. Seeds are the same fixed "
                 f"list 0–9 in every configuration.", "", "**Summary**", ""] + summary +
                ["", "**Per seed**", ""] +
                md(rows, ["configuration", "epochs", "seed", "final train loss", "test R²",
                          "passed filter"]))


def t8() -> None:
    gs, gc = load("kan_grid_sweep"), load("kan_grid_confound")
    rows = []
    for g in gs["grids"]:
        pg = gs["per_grid"][str(g)]
        h = pg["h_affine_residual"]
        b = gc["banded"].get(str(g))
        rows.append([str(g), str(pg["convergence"]["n_well_converged"]),
                     str(pg["n_usable_gauge_pairs"]),
                     f"{h['mean']:.4f}" if h else "n/a",
                     f"{pg['convergence']['test_r2']['mean']:.4f}",
                     (f"{b['h_mean']:.4f}" if b else "n/a"),
                     (str(b["n"]) if b else "0")])
    write_table("T8_grid_sweep_with_matching.md",
                ["kan_grid_sweep", "kan_grid_confound"],
                "T8. Grid sweep, unmatched vs fit-quality-matched",
                ["**T8.** d=1 grid sweep. The unmatched column reproduces the apparent monotone "
                 "trend; the matched column restricts to pairs with comparable fit quality "
                 "(min pair R² ∈ [0.99, 1.0]) so that grid is the only thing differing.", "",
                 f"Correlations over all {gc['n_pairs']} usable pairs: "
                 f"corr(log₂ grid, h-vs-affine) = **{gc['corr_log2grid_h']:+.4f}**, "
                 f"corr(min pair R², h-vs-affine) = **{gc['corr_minr2_h']:+.4f}**. "
                 f"Monotone within the matched band: **{gc['band_monotonic']}**.", ""] +
                md(rows, ["grid", "n well-conv. seeds", "n gauge pairs",
                          "h-vs-affine (unmatched)", "mean test R²",
                          "h-vs-affine (matched band)", "n pairs (band)"]))


# ──────────────────────────────── figures ───────────────────────────────────

def f1() -> None:
    src = RES / "kan_composition_gauge_d1.png"
    (FIG / "F1_parametric_phi1_d1.png").write_bytes(src.read_bytes())
    print("  wrote figures/F1_parametric_phi1_d1.png (copied from committed result figure)")


def f2() -> None:
    npz = FIG / "data" / "d2_layer1_curves.npz"
    if not npz.exists():
        print("  SKIP F2: figures/data/d2_layer1_curves.npz missing")
        return
    z = np.load(npz)
    seeds = [int(s) for s in z["seeds"]]
    r2 = {s: float(r) for s, r in zip(seeds, z["r2"])}
    wc = [s for s in seeds if r2[s] > R2_THRESHOLD]
    ref = wc[0]
    fig, ax = plt.subplots(2, 2, figsize=(12, 8))
    for s in seeds:
        ok = s in wc
        st = dict(alpha=0.85, lw=1.5) if ok else dict(alpha=0.3, lw=0.9, ls=":")
        ax[0, 0].plot(z["x1"], z[f"s{s}_x1"], **st)
        ax[1, 0].plot(z["x2"], z[f"s{s}_x2"], **st)
    for s in wc:
        fit = raw_and_quotiented(z[f"s{ref}_x1"], z[f"s{s}_x1"])  # ref ~ a*s + b, from x1 ONLY
        a, b = fit["a"], fit["b"]
        ax[0, 1].plot(z["x1"], a * z[f"s{s}_x1"] + b, alpha=0.85, lw=1.5)
        ax[1, 1].plot(z["x2"], a * z[f"s{s}_x2"] + b, alpha=0.85, lw=1.5)
    ax[0, 0].set_title("layer1 x1-edge, raw (dotted = not well-converged)")
    ax[0, 1].set_title(f"x1-edge after per-seed affine align to seed {ref}")
    ax[1, 0].set_title("layer1 x2-edge, raw")
    ax[1, 1].set_title("x2-edge under the SAME transform fitted on x1")
    for a_ in ax.ravel():
        a_.grid(alpha=0.25)
    fig.suptitle("F2. Additive d≥2: one shared affine map aligns BOTH edges of the node")
    fig.tight_layout()
    fig.savefig(FIG / "F2_d2_edges_shared_affine.png", dpi=130)
    plt.close(fig)
    print("  wrote figures/F2_d2_edges_shared_affine.png")


def f3() -> None:
    m = load("kan_multiplicative")
    P, A, PW = [], [], []
    for r in m["pairs"]:
        for e in r["edges"].values():
            if e.get("inconclusive"):
                continue
            P.append(e["p"]); A.append(e["affine_residual_full"]); PW.append(e["power_residual"])
    P, A, PW = np.array(P), np.array(A), np.array(PW)
    dev = np.abs(P - 1.0)
    fig, ax = plt.subplots(1, 2, figsize=(12, 4.6))
    ax[0].scatter(dev, A, s=34, label="affine quotient", alpha=0.85)
    ax[0].scatter(dev, PW, s=34, marker="s", label="power quotient", alpha=0.85)
    ax[0].set_yscale("log"); ax[0].set_xlabel("|p − 1|"); ax[0].set_ylabel("residual")
    ax[0].set_title("per edge-fit"); ax[0].legend(); ax[0].grid(alpha=0.25)
    edges, cent, am, pm = [(0, .15), (.15, .5), (.5, 1.), (1., 1e9)], [], [], []
    lbls = []
    for lo, hi in edges:
        k = (dev >= lo) & (dev < hi)
        if k.sum():
            cent.append(len(cent)); am.append(A[k].mean()); pm.append(PW[k].mean())
            lbls.append(f"[{lo},{hi})" if hi < 1e8 else "[1.0,∞)")
    w = 0.36
    ax[1].bar(np.array(cent) - w/2, am, w, label="affine")
    ax[1].bar(np.array(cent) + w/2, pm, w, label="power")
    for i, (a_, p_) in enumerate(zip(am, pm)):
        ax[1].text(i, max(a_, p_) * 1.1, f"{a_/p_:.1f}×", ha="center", fontsize=9)
    ax[1].set_xticks(cent); ax[1].set_xticklabels(lbls); ax[1].set_yscale("log")
    ax[1].set_xlabel("\\|p − 1\\| stratum"); ax[1].set_ylabel("mean residual")
    ax[1].set_title("stratified means (power advantage annotated)")
    ax[1].legend(); ax[1].grid(alpha=0.25, axis="y")
    fig.suptitle("F3. Affine is the p≈1 slice of the power group; the two separate as |p−1| grows")
    fig.tight_layout()
    fig.savefig(FIG / "F3_power_stratification.png", dpi=130)
    plt.close(fig)
    print("  wrote figures/F3_power_stratification.png")


def f4() -> None:
    configs = []
    gs = load("kan_grid_sweep")
    for g in gs["grids"]:
        configs.append((f"d=1 grid={g}\n(600 ep)",
                        {s["seed"]: s["test_r2"] for s in gs["per_grid"][str(g)]["per_seed"]}))
    configs.append(("d≥2 [2→1→1]\n(3000 ep)",
                    {s["seed"]: s["test_r2"] for s in load("kan_multivariate")["per_seed"]}))
    configs.append(("mult [2→1→1]\n(3000 ep)",
                    {s["seed"]: s["test_r2"] for s in load("kan_multiplicative")["per_seed"]}))
    fig, ax = plt.subplots(figsize=(11, 5))
    for i, (label, d) in enumerate(configs):
        xs = [i + (s - 4.5) * 0.055 for s in sorted(d)]
        ys = [d[s] for s in sorted(d)]
        cols = ["tab:green" if y > R2_THRESHOLD else "tab:red" for y in ys]
        ax.scatter(xs, ys, c=cols, s=42, zorder=3)
        for x, y, s in zip(xs, ys, sorted(d)):
            if y <= R2_THRESHOLD:
                ax.annotate(str(s), (x, y), fontsize=7, xytext=(0, -11),
                            textcoords="offset points", ha="center", color="tab:red")
    ax.axhline(R2_THRESHOLD, ls="--", c="k", lw=1, label=f"filter: R² = {R2_THRESHOLD}")
    ax.set_xticks(range(len(configs)))
    ax.set_xticklabels([c[0] for c in configs], fontsize=9)
    ax.set_ylabel("test R²"); ax.set_yscale("logit")
    ax.set_title("F4. Per-seed convergence by configuration (red = filtered out, labelled by seed)")
    ax.grid(alpha=0.25); ax.legend(loc="lower left")
    fig.tight_layout()
    fig.savefig(FIG / "F4_convergence_census.png", dpi=130)
    plt.close(fig)
    print("  wrote figures/F4_convergence_census.png")


def check_draft() -> int:
    """draft.md inlines the generated tables so it reads standalone. This verifies no
    inlined row has drifted from tables/. Run after regenerating. T7 is inlined only as
    a summary (60 rows), so its per-seed rows are exempt."""
    import re
    draft = (OUT / "draft.md").read_text()

    def rows(txt: str) -> list[tuple]:
        out = []
        for ln in txt.splitlines():
            ln = ln.strip()
            if ln.startswith("|") and not re.match(r"^\|[\s\-:|]+\|$", ln):
                out.append(tuple(c.strip() for c in ln.strip("|").split("|")))
        return out

    draft_rows = set(rows(draft))
    bad = 0
    for f in sorted(TAB.glob("T*.md")):
        if f.name.startswith("T7"):
            continue
        for r in rows(f.read_text()):
            if len(r) >= 2 and r not in draft_rows:
                print(f"  DRIFT [{f.name}]: {r}")
                bad += 1
    print("  draft.md matches tables/" if bad == 0 else f"  {bad} row(s) drifted -- re-inline them")
    return bad


def main() -> None:
    TAB.mkdir(parents=True, exist_ok=True)
    (FIG / "data").mkdir(parents=True, exist_ok=True)
    if "--check" in sys.argv:
        print("checking draft.md against tables/:")
        raise SystemExit(1 if check_draft() else 0)
    print("tables:")
    for fn in (t1, t2, t3, t4, t5, t6, t7, t8):
        fn()
    print("figures:")
    for fn in (f1, f2, f3, f4):
        fn()
    print("consistency:")
    check_draft()


if __name__ == "__main__":
    main()
